import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FormularioEventoProvider } from "../context/FormularioEventoContext";
import { MateriaisProvider } from "../context/CadastrarMaterialContext";
import { Lexend } from "next/font/google";

const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${lexend.variable} ${geistSans.variable} ${geistMono.variable} font-sans`}>
        <FormularioEventoProvider>
          <MateriaisProvider>
            {children}
          </MateriaisProvider>
        </FormularioEventoProvider>
      </body>
    </html>
  );
}
